---
language: node_js
node_js:
  - '0.10'

# We need a running MongoDB instance for integration tests for the MongoDB
# backend.
services:
  - mongodb

before_script:
  - npm install -g jasmine-node@~1.2.3
  - npm install -g cucumber@~0.3.0
  - npm install -g grunt-cli

branches:
  only:
    - master
